data_dir: "processed_sentinel2"
num_classes: 2

rgb_channels: 3
msi_channels: 9

# Training configuration
epochs: 300
batch_size: 8
learning_rate: 0.001
weight_decay: 0.0001
poly_power: 0.9

# Loss configuration
use_class_weights: true
road_weight: 8.0

# Data loading
num_workers: 4

# Logging and checkpoints
log_dir: "logs_sentinel2"
checkpoint_dir: "checkpoints_sentinel2"

# Hardware
device: "cuda"

# Validation split
train_split: 0.8
val_split: 0.2

# Validation configuration
val_frequency: 5
save_frequency: 10

# Transfer Learning
transfer_learning:
  enabled: false
  pretrained_path: "checkpoints/best.pth"
  freeze_encoder: false
  freeze_cffm: false

# Sentinel-2 specific
sentinel2:
  target_resolution: 10
  osm_buffer_meters: 5
  
# Data augmentation
augmentation:
  enabled: false
  rotation: true
  flip: true
  brightness: 0.1
  contrast: 0.1
  gamma: 0.1