data_dir: "processed_data"
num_classes: 2

model_width: 32

epochs: 100
batch_size: 4
learning_rate: 0.001
weight_decay: 0.0001
poly_power: 0.9

use_class_weights: true

# Workers are the number of threads that will be used to load the data
num_workers: 4

log_dir: "logs"
checkpoint_dir: "checkpoints"

device: "cuda"

train_split: 0.8
val_split: 0.2

seed: 42

val_frequency: 5
save_frequency: 10